# Generated by Django 6.0.6 on 2026-07-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Prepaid (Razorpay)'), ('cod', 'Cash on Delivery')], default='razorpay', max_length=20),
        ),
    ]
