# Generated by Django 6.0.6 on 2026-07-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.JSONField(blank=True, default=dict, help_text='Stock per size, e.g. {"7": 3, "8": 0, "9": 5}'),
        ),
    ]
