# Generated by Django 6.0.6 on 2026-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_stock_restored_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Case-insensitive, e.g. BUILT10', max_length=30, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='e.g. 10 for 10% off')),
                ('active', models.BooleanField(default=True)),
                ('min_order_value', models.PositiveIntegerField(blank=True, help_text='Minimum subtotal (INR) required to use this code', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
